### ISSUE TITLE
7th week: The logical scheme of the database, the physical model of the data

### ISSUE THREAD

**Issue by kolpakovd** [kolpakovd/BiometricACS#11]

**Comment by kolpakovd** [comment]
Изменил чуть логическую схему, добавив статус сотруднику. Пока что не буду привязывать аккаунт к конкретному человеку и фиксировать логи системы в бд. Это надо еще хорошо обдумать...

### Логическая схема данных
![logic data schema](https://user-images.githubusercontent.com/32396320/46171778-4143ee80-c2aa-11e8-8644-0767735adc1d.png)

(хоть не совсем по теме) так же изменил концептуальную, добавив некоторые поля...
<spoiler> ![onceptual data schema](https://user-images.githubusercontent.com/32396320/46171870-7c462200-c2aa-11e8-8fd6-eeaf60af8da8.png) </spoiler>

**Comment by wldmr-key** [comment]
1) концептуальная схема должна быть понятна даже идиоту, а ты ориентируешься на полиглотов с развитыми интуитивными способностями. Убери нафиг здесь свой английский - все-равно в РПЗ придется переделывать! К тому же с такими названиями атрибутов к концептуальной схеме надо глоссарий писать. И слово аддресс, да.
2) второй раз намекаю, что связь между событиями проходной и камерами у тебя нарисована неправильно

**Comment by kolpakovd** [comment]
Исправил...

**Comment by wldmr-key** [comment]
как я говорил на лекции, если у тебя сущность отвязана от остальных, то вряд ли она имеет концептуальное значение

**Comment by kolpakovd** [comment]
Исправил
