### ISSUE TITLE
10th week: Development of the design part

### ISSUE THREAD

**Issue by kolpakovd** [kolpakovd/BiometricACS#13]
Релиз-кандидат 
[Проектно-конструкторская часть.docx](https://github.com/kolpakovd/BiometricACS/files/2659876/-.docx)

**Comment by wldmr-key** [comment]
нормально, но возникнут вопросы
Логическая схема - как всегда, висящие в одиночестве эккаунты и отсутствие фиксации событий пропуска людей, не являющихся сотрудниками предприятия
Графику постарайся рисовать так, чтобы дуги не сходились в одну точку
Твои алгоритмы - это линейные последовательности. Условные действия намеренно игнорируются?
Что такое 20фпс? Это производительность всего конвейера? я, например, сразу спрошу, кто является слабым звеном? ))

**Comment by wldmr-key** [comment]
с эккаунтами поступай, как хочешь. Оба исхода вызовут вопросы. Но ты же ответишь?
С логгированием хуже. Резонным вопросом будет - зачем тебе две системы фиксации событий? Со всеми вытекающими последствиями
