### ISSUE TITLE
14th week: Development of design and technological part

### ISSUE THREAD

**Issue by kolpakovd** [kolpakovd/BiometricACS#14]
Rc1.1
[Проектно-технологическая часть.docx](https://github.com/kolpakovd/BiometricACS/files/2660032/-.docx)

**Comment by wldmr-key** [comment]
ну, нормально пока

**Comment by wldmr-key** [comment]
а это все? У тебя объем набирается?

**Comment by kolpakovd** [comment]
Минимум 22 листа набирается без приложений, титульников и содержаний
