### ISSUE TITLE
Summaries

### ISSUE THREAD

**Issue by kolpakovd** [kolpakovd/BiometricACS#15]
РПЗ, ничего не изменено в частях, склеено в единый файл
[РПЗ.docx](https://github.com/kolpakovd/BiometricACS/files/2669380/default.docx)

Презентация, приложения к рпз будут в течение ночи.
Вот пример работы системы обработки видеопотока)
<details> 
Как вы говорили, что "вахтеру" не очень интересно будет смотреть на полученные характерные точки и нормализацию поворота - есть возможность скрыть это :)

![b1o5suzib00](https://user-images.githubusercontent.com/32396320/49830018-12b1bc00-fda1-11e8-8629-c3ee259e2065.jpg)
</details>

**Comment by kolpakovd** [comment]
<a href="https://github.com/kolpakovd/BiometricACS/blob/master/Docs/%D0%9F%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D1%8F.pptx">Презентация</a>

Приложения: 
- <a href="https://github.com/kolpakovd/BiometricACS/blob/master/Docs/DrawingsScreenshots/%D0%9A%D0%BE%D0%BC%D0%BF%D0%BE%D0%BD%D0%B5%D0%BD%D1%82%D1%8B%20%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B3%D0%BE%20%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81%D0%B0.png">Компоненты графического интерфейса</a>

- <a href="https://github.com/kolpakovd/BiometricACS/blob/master/Docs/DrawingsScreenshots/%D0%A1%D1%85%D0%B5%D0%BC%D0%B0%20%D0%BF%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81%D0%B0%20%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8%20%D0%B2%D0%B8%D0%B4%D0%B5%D0%BE%D0%BF%D0%BE%D1%82%D0%BE%D0%BA%D0%B0.png">Схема обработки видеопотока</a>

- <a href="https://github.com/kolpakovd/BiometricACS/blob/master/Docs/DrawingsScreenshots/%D0%A1%D1%85%D0%B5%D0%BC%D1%8B%20%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85.png">Схемы данных</a>

**Comment by wldmr-key** [comment]
По листам - все ок за исключением склеенных стрелок, ок которых я уже устал всем говорить
По презентации - есть большое подозрение, что ты не уложишься по времени. Я бы предложил выкинуть требования к техническому обеспечению (или хотя бы не выкатывать их в начале) и половину слайдов про интерфейс (жалко трудов - перемести их после последнего листа презентации и, если будет время -покажешь)

**Comment by wldmr-key** [comment]
РПЗ пойдет. Титульник, нормальное оглавление и ссылки на литературу, надеюсь, появятся
