### ISSUE TITLE
4th week: Final version of the technical task

### ISSUE THREAD

**Issue by kolpakovd** [kolpakovd/BiometricACS#3]
In developing ...

**Comment by kolpakovd** [comment]
[technical task (rus language).docx](https://github.com/kolpakovd/BiometricACS/files/2406601/technical.task.rus.language.docx)

**Comment by kolpakovd** [comment]
Сделал, переделал, доделал
 ```
1.4 здесь этапность не приводится
2.2. Из четырех заявленных тобой целей могу принять только полторы:
"Усиление контроля пропуска" - считается за половину из-за очень невнятной формулировки. При должной фантазии можно догадаться что имеется в виду. Что можно считать достижением этой цели?
"Замещение рабочих мест на всех подключенных пунктах пропуска одним" - это хорошая, годная, объяснимая и проверяемая цель
Все остальное - как цели трактоваться не могут. Понятно, почему?
3. Не хватает подробностей о том, что такое пункты пропуска. Там сидит вахтер, который нажимает на кнопку? Автоматические турникеты? Замки, решетки, капканы? Поток людей? Каких? Сотрудников, наверное? Цель этого пункта - сформулировать четкие исходные условия и термины, не вызывающие вопросов.
Подраздел "условия эксплуатации" тебе по барабану? освещенность, температура и влажность, например...

4.1.6 то есть, бэкапов делать не надо? :)
4.2. "Задача всей системы забивается на задачи ее подсистем" ну-ну...
А посмотреть, кто-куда-когда ходил можно будет? Отчеты там, какие-нибудь, а?

4.3.2 "Будут" плохое слово для требования. "Должны"?
4.3.3 Техническое обеспечение сервера? это все?

7 для ввода системы в действие биометрику снимать не нужно будет?
 ```
(Сами разберутся), функционал позволяет собирать биометрические данные в автоматическом режиме, а так же в полуавтоматическом (нажать на кнопочку и выбрать сотрудника, который стоял возле камеры) и в ручном (загрузка фотки и выбор сотрудника к этой фотке).
Либо я не так понимаю суть этого вопроса.
 ```
4.1.1 взаимодействия с кадровой системой предприятия не планируется?
 ```

Не очень понимаю суть термина "математическое обеспечение" - это калькуляторы\библиотеки машинного обучения\алгоритмы перемножения матриц?
 ```
4.3.1 Так что требуется-то в этом подразделе?
 ```

**Comment by wldmr-key** [comment]
продолжаем мучить 2.2.

> Замещение текущей системы пропусков (или объединение с ней);

революция ради революции?  Зачем? наверное, у старой системы есть какие-то плохие качества, а у новой их нет. Тогда и нужно ставить целью избавление от плохого или достижение хорошего.

> Повышение контроля пропуска

это можно измерить? как? Продолжение "путем введения" в целях никогда не употребляется. Цель - это желание чего-то конкретного добиться, а каким путем - в этом разделе не важно.

---

> 4.2... •	Подсистема принятия решений анализирует выделенные биометрические данные и принимает решение о подаче сигнала на пропускающую единицу, передавая положительные решения подсистеме ведения журнала посещения;

представляется небесполезным (и для отстройки системы, и для обеспечения безопасности) фиксировать и отрицательные решения)

---

> 4.3.1. Не очень понимаю суть термина "математическое обеспечение" - это калькуляторы\библиотеки машинного обучения\алгоритмы перемножения матриц?

УКАЗАНИЯ ГОСТ:
Для математического обеспечения системы приводят требования к составу, области применения (ограничения) и способам, использования в системе математических методов и моделей, типовых алгоритмов и алгоритмов, подлежащих разработке. (_я это скопировал отсюда (http://www.rugost.com/index.php?option=com_content&view=article&id=108:34-4-8&catid=25:6#4_3_1) - посмотри - это полезно и для следующих пунктов. Там есть и рекомендации по **формальному содержанию**, но им можно следовать только в случае полной безысходности_)

То, что написано у тебя - ниачем. Если тебе известны конкретные модели, которые требуется использовать в этой системе, так и напиши. Если нет, то напиши, что их требуется подобрать или разработать в соответствии с требованиями к качеству (которых нет, кстати). 

не очень понятно отсутствие требований к информационному обеспечению

**Comment by kolpakovd** [comment]
```
"Замещение текущей системы пропусков (или объединение с ней);"
революция ради революции? Зачем? наверное, у старой системы есть какие-то плохие качества, а у новой их нет. Тогда и нужно ставить целью избавление от плохого или достижение хорошего.
```
Ну может же быть революция после революции. Конечно у старой системы есть плохие качества - наличие вахтеров на каждом КПП и наличие электронных карточек у всех работников. А на счет объединения - разрабатываемая система может служить как второй (мб первый) фактор защиты входа.
Оставил 1 цель...

Остальное исправил, добавил

```
**4.3.1 Требования к математическому обеспечению системы**
Математическое обеспечение всей системы заключено в подсистеме обработки видеопотока. В данной подсистеме должен быть подобран ряд математических моделей нейронных сетей и алгоритмов компьютерного зрения, решающих поставленную задачу обработки данных с ученом условия обработки потока данных в реальном времени.

**4.3.2 Требования к информационному обеспечению**
Состав, структура и способы организации данных в системе должны быть определены на этапе технического проектирования.
Уровень хранения данных в системе должен быть построен на основе современных реляционных или объектно-реляционных СУБД. Для обеспечения целостности данных должны использоваться встроенные механизмы СУБД. 
Доступ к данным должен быть предоставлен только авторизованным пользователям с учетом их служебных полномочий, а также с учетом категории запрашиваемой информации.
```

v 1.0rc1
[technical task (rus language).docx](https://github.com/kolpakovd/BiometricACS/files/2407112/technical.task.rus.language.docx)

**Comment by wldmr-key** [comment]
ок, вполне себе релиз-кандидат
Вторую цель ты сам себе хорошо обозначил - сокращение статьи расходов на бумажные пропуска или электронные карточки

> 4.1.6 Требования по сохранности информации при авариях
> Система **будет** иметь возможность создания резервных копий данных.

должна!!! - это требование, а не прогноз!

**Comment by kolpakovd** [comment]
Испр. доп.
v 1.0rc2
[technical task (rus language).docx](https://github.com/kolpakovd/BiometricACS/files/2407988/technical.task.rus.language.docx)
