### ISSUE TITLE
4th week: Сonceptual data schema

### ISSUE THREAD

**Issue by kolpakovd** [kolpakovd/BiometricACS#4]
In developing ...

**Comment by wldmr-key** [comment]
я рад, что мои пламенные речи о неприемлемости id в концептуальных схемах нашли свой отклик, но даже в концептуальной схеме нужны идентифицирующие атрибуты у сущностей. Я имею в виду, что у работников таковым может быть табельный номер (как правило) или его суррогат.
Я бы выделил сущности department (кстати, она не иерархическая ли, случаем?) и employee, как внешние по отношению к твоей системе (они формируются и поддерживаются где-то далеко - в отделе кадров)
Что за странная связь между Visit и Camera?
Прими во внимание фактор времени - как думаешь, статус работников со временем меняется?
Вход в систему для вахтера - это начало дежурства. Это событие нигде не стоит фиксировать?
Инциденты в системе не фиксируются?

**Comment by kolpakovd** [comment]
Его включать только в концептуальную схему или в логической тоже отображать? 
> Я имею в виду, что у работников таковым может быть табельный номер (как правило) или его суррогат.

Забыл написать, что эти 2 сущности _имитируют внешнюю бд отдела кадров_
> Я бы выделил сущности department (кстати, она не иерархическая ли, случаем?) и employee, как внешние по отношению к твоей системе (они формируются и поддерживаются где-то далеко - в отделе кадров)

Что бы знать через какой конкретно турникет прошел работник и в какую сторону (вошел\вышел).
> Что за странная связь между Visit и Camera?

Как это может сказаться на работоспособности системы, не очень понимаю...
Аккаунты заводятся все зависимости от конкретного работника. У аккаунтов будут роли по типу - Viewer, TechnicalEngineer. Такие роли разграничивают доступ к некоторому функционалу программы.
> Прими во внимание фактор времени - как думаешь, статус работников со временем меняется?

В бд фиксировать не планировал. Фиксируются в логах сессии в главном окне. Если нужно - выгрузят сессию логов через пункт в меню. (ИМХО - не уверен, но кажется логи программ не хранятся в бд...)
> Вход в систему для вахтера - это начало дежурства. Это событие нигде не стоит фиксировать?
Инциденты в системе не фиксируются?
