### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by kolpakovd** [kolpakovd/BiometricACS#6]

**Comment by kolpakovd** [comment]
```
"Так же, у меня в моем приложении есть функция авторизации, стоит ли ее прикручивать к пользователям бд (постгрес), у которых есть права на insert/update/delete, тогда не нужно будет пилить функцию регистрации или лучше создать таблицу с зарегистрированными пользователями данной программы, а транзакции производить от пользователя Postgres?"

Лучше второе - давать доступ к БД напрямую - плохая практика

```
По поводу таких мувов - меня смущает это, система должна быть защищена от левых людей, т.к.  в системе будут параметры настройки, напрямую регулирующие систему принятия решений.
Есть идея вообще 'поставлять' такую систему с 1 аккаунтом, конечно же уникальным.

**Comment by wldmr-key** [comment]
один эккаунт и для инженера по настройке, и для вахтера? Боюсь, это не поймут...

**Comment by kolpakovd** [comment]
Еще такое предложение, что бы не флудить в issue по поводу еженедельных спринтов - создал [доску](https://github.com/kolpakovd/BiometricACS/projects/1), если я буду помещать таски недельные в выполняемые и в завершенные, а после окончания спринта недельного и выставления зеленой клеточки в списке группы - буду бросать завершенные таски в архив.  А для этапных заданий (4, 7, 10, 14 недели) буду создавать отдельные топики в issue под отдельным этапом (Milestones)
Такой team building устроит?)
```
2. Длина спринта - одна неделя
Задание на спринт желательно составлять самому в репозитории проекта. Иначе его буду оценивать я, исходя из собственных секретных соображений (соображения на 4, 7, 10 и 14 неделю несекретны и изложены в методичке)
```

**Comment by wldmr-key** [comment]
> Вахтеры уволены. - Я предполагал, что такая система заменил всех этих вахтеров одним человеком, который будет нажимать на кнопочку ручного открытия турникетов и создавать отчетности по посещению работников, если это потребуется; во всем остальном система автономна.

Ты же сам понимаешь, что один человек не может работать в режиме 24х365, а ответственность за пропуск левого лица на территорию должна быть персональной. вряд ли вахтеры составляют отчеты и вряд ли просмотр отчетов должен быть доступен уборщице. так что одного эккаунта явно мало

**Comment by wldmr-key** [comment]
> Такой team building устроит?)

Вот это, как раз, типичный флуд :) не по теме задачи. Нужно было создать отдельную задачу типа согласование режима взаимодействия по спринтам

По существу - да, устроит, о у тебя там уже мешок задач явно не на текущий спринт. Так что нужно либо ставить ярлыки, либо вводить еще один контейнер для текущего спринта

**Comment by kolpakovd** [comment]
```
у тебя там уже мешок задач явно не на текущий спринт.
```
Добавил колонку с тасками, которые реализую на текущем этапе, но при переходе на следующий этап (не спринт), на котором должны быть реализованы эти таски - закину их в завершенные.

**Comment by kolpakovd** [comment]
Как лучше сделать со строкой подключения - хардкодить в питоновский файл или вынести в файл с настройками всей программы? Или есть другой более правильный путь?

**Comment by wldmr-key** [comment]
1.  Конечно, внешний файл
2. Доступ к БД осуществляется через представления и функции.
3. Это очень сильно зависит от юзкейсов. Если вахтеру, нужно одновременно пялится в камеру и шарить по спискам и еще что-то, то ответ очевиден. Если нет, то тоже ))

**Comment by kolpakovd** [comment]
Итак. Возникла следующая проблема:
Что бы получить кадр с камеры в python opencv нужно инициализировать объект VideoCapture и передать в качестве аргумента либо путь к файлу, либо айпи (для айпи-камер), либо индекс видео устройства. Так вот, т.к. пишу систему не на линуксе, где "всё" является файлом и можно передавать в VideoCapture путь к файлу девайса из каталога /dev/, а на винде, то нужно в качестве аргумента подавать индекс устройства. 
Проблема состоит в привязке конкретного устройства к этому индексу. Ведь при отсоединении\присоединении камеры из юсб порта, у каждой камеры меняется тот самый индекс.
На данный момент я  могу получить список имен подключенных видеокамер (при помощи кода на плюсах, который специально сделан под питоновский модуль), индекс камеры получаю как индекс элемента в этом списке. Но при различной последовательности включений камеры в различные юсб порты - этот список имеет не правильный порядок элементов.
Так вот, как быть (как получить индекс камеры по названию\PID&VID устройства) ?(

**Comment by wldmr-key** [comment]
Никак не отличить. У usb камер нет имен и ид у однотипных камер одинаковы. Более того, их индексы вполне могут поменяться также и при перезагрузке
Варианты:
1) проигнорировать проблему, так как в боевом варианте нужно задействовать ip-камеры - нет смысла ставить компьютер
2) разрулить ситуацию тем, что обязать ставить разнотипные камеры в одном помещении
3) самый экзотичный - определять ориентацию камеры по статичному фону
4) раз есть вахтер, то он может сделать это и вручную

**Comment by kolpakovd** [comment]
Могу ли изменить описание одной из подсистем, указанных в ТЗ?
>•	Подсистема ведения журнала посещения, при получении данных, взаимодействует с базой данных, записывая в нее историю проходов через определенный пункт пропуска.

"Подсистема логгирования. Отслеживает события, происходящие в системе, записывая их в базу данных и файлы логов"

**Comment by wldmr-key** [comment]
запросто
