### ISSUE TITLE
4th week: Prototypes of interfaces

### ISSUE THREAD

**Issue by kolpakovd** [kolpakovd/BiometricACS#7]

**Comment by wldmr-key** [comment]
Я бы предложил набросать то, что видится в настоящий момент. Скетч интерфейса ни к чему не обязывает, но может прояснить часть проблем.

**Comment by kolpakovd** [comment]
![windowcreateaccountpanel](https://user-images.githubusercontent.com/32396320/45972103-86b2b280-c043-11e8-851a-08b5c9c8c149.png)
![windowloginpanel](https://user-images.githubusercontent.com/32396320/45972104-86b2b280-c043-11e8-8ce2-60466a57ecda.png)
![windowmain1](https://user-images.githubusercontent.com/32396320/45972108-874b4900-c043-11e8-9d87-fec730de566c.png)
![windowmain2](https://user-images.githubusercontent.com/32396320/45972111-87e3df80-c043-11e8-95b0-a1e8d695d900.png)
![windowmain3](https://user-images.githubusercontent.com/32396320/45972112-87e3df80-c043-11e8-935a-f207c1782882.png)

### Панель меню:
File 
> Export, Exit
> Export -> _Session log_

Control

> Data, Settings, Accounts
> Data -> _Add biometrics data, Backing up data_
> Settings -> _Open panel, Import, Export_
> Accounts -> _Relogin, Create, Export Accounts_


### Примеры:


![windowmain_example1](https://user-images.githubusercontent.com/32396320/45972105-874b4900-c043-11e8-89fc-efe3d4ec6694.png)
![windowmain_example2](https://user-images.githubusercontent.com/32396320/45972106-874b4900-c043-11e8-8ee0-dbb769cfbf61.png)
![windowmain_example3](https://user-images.githubusercontent.com/32396320/45972107-874b4900-c043-11e8-8536-f1cc1603158e.png)

**Comment by wldmr-key** [comment]
ок. В качестве скетчей пойдет, хотя...
0. Совет: когда рисуешь скетчи, а, особенно, когда делаешь отчеты/презентации и прочую публичность **обязательно** заполняй все формы правдоподобными данными. _Ты правильно сделал_, что привел примеры форм. _Ты неправильно сделал_, что выкатил пустые формы
1. Ты пишешь, что один вахтер заменит 5 (или 10, или 15?). Судя по главному окну, ему будет это сделать нелегко... Какой из 5 потоков он будет наблюдать? Будут ли ему поступать какие-то алерты в случае проблем?
2. Вахтеров будешь нанимать со знанием английского? что у нас будет с локализацией?
3. Вахтерам нужны характерные биометрические точки?
4. В статистике поиск/фильтры и прочие штучки, которые так любят преподаватели баз данных, будут?

**Comment by kolpakovd** [comment]
Который он выбрал, на примере - синий цвет. Зачем ему наблюдать одновременно на всеми камерами, а если их 100500... "Вахтер" обслуживает эту систему только тогда, когда нужно вручную открыть турникеты, нажав на кнопку, либо когда нужно добавить нового человека в бд - тогда снятие биометрических данных будет производиться сразу с видеопотока камеры. В принятии решения система автономна.
> Какой из 5 потоков он будет наблюдать? 

Хороший вопрос, скорее всего сделаю какую-нибудь оповещалку в виде, которая выскакивает на экран, если камера посреди рабочего дня вышла из строя.
> Будут ли ему поступать какие-то алерты в случае проблем?

Изначально пишу на английском, в будущем добавлю локализацию в одном из обновлений. Кстати, qt дизайнер при генерации питоновского кода добавляет метод локализации :)
> Вахтеров будешь нанимать со знанием английского? что у нас будет с локализацией?

Навряд ли. Добавил - потому что. <del>Так красиво</del>. Интерфейс с двумя квадратными окнами выглядит не очень...
> Вахтерам нужны характерные биометрические точки?

Разнообразие статистики, которой можно придумать - практически бесконечность...
Добавлю конкретные фичи фильтрации&поиска на усмотрение заказчика.
А так добавлю поиск по отделу, по событию (вошел, вышел) и еще по чему-нибудь...выгрузку всех событий...
> В статистике поиск/фильтры и прочие штучки, которые так любят преподаватели баз данных, будут?
