### ISSUE TITLE
7th week: Design of the research part

### ISSUE THREAD

**Issue by kolpakovd** [kolpakovd/BiometricACS#8]

**Comment by wldmr-key** [comment]
Вообще-то я на 6-ой неделе ожидаю хоть каких-то целостных результатов. На седьмой неделе все должно быть уже оформлено
Где описание процессов системы?

**Comment by kolpakovd** [comment]
pre-alfa v1.0
 [Исследовательская часть.docx](https://github.com/kolpakovd/BiometricACS/files/2484469/default.docx)

**Comment by wldmr-key** [comment]
ну-да, ну-да, конечно, преальфа ))
понимаешь, описание предметной области - это не про сущности (для начала = второго абзаца) и не про нейронные сети (это - туда - к алгоритмам). Это про людей и процессы
Кто и когда входит/выходит? Что с ними делать? Кто за что отвечает и, наконец, какие процессы и как автоматизируются? В каком значении ты употребляешь неочевидные понятия?
Без этого не очень понятно, в частности, распределение функций. Что это за "статистический поиск" доступный вахтеру, как выясняется? Перекрестную энтропию он подсчитывать должен? Зачем технический инженер должен сотрудников впускать с его-то зарплатой?
Я даже не могу тебе сказать "прочитай методичку" - ты ее явно читал, но постарайся сделать так, чтобы написанный тобой текст не вызывал вопросов у неподготовленного человека

**Comment by kolpakovd** [comment]
Вахтеры уволены. Есть "наблюдатель" за системой и процессом прохода, который может пользоваться поиском посещений, формировать из него статистику и отправлять куда надо (руководству к примеру).
'''
 Что это за "статистический поиск" доступный вахтеру, как выясняется?
'''

На то он и технический инженер, что ему доступен весь функционал системы.
'''
Зачем технический инженер должен сотрудников впускать с его-то зарплатой?
'''

[Исследовательская часть.docx](https://github.com/kolpakovd/BiometricACS/files/2654397/default.docx)

**Comment by wldmr-key** [comment]
пойдет. Намекаю,что пора уже заканчивать курсовую
